export const data = {
  meta: {
    types: [
      "Opdracht",
      "Stemrecht",
      "Never Have I Ever",
      "Most Likely To",
      "Medusa",
      "Lepeltje Lepeltje",
      "Vingeren",
      "Big",
      "Baas",
    ],
    colors: [
      "#9BE077",
      "#FCC8FC",
      "#A8D9F4",
      "#A8D9F4",
      "#282828",
      "#FCC8FC",
      "#FCC8FC",
      "#F98F8F",
      "#9BE077",
    ],
    probabilities: [30, 25, 20, 20, 20, 10, 10, 10, 10],
  },
  cards: [
    // Opdracht
    [
      "Hey %p, neem %a0 slokken!",
      "Hey %p, de speler links van jou neemt %a0 slokken!",
      "Hey %p, de speler rechts van jou neemt %a0 slokken!",
      "Hey %p, de speler tegenover jou neemt %a0 slokken!",
      "Hey %p, kies een andere speler uit, die speler neemt %a0 slokken!",
      "Hoi %p, je mag samen met %p %a0 slokken verdelen over de andere spelers!",
      "Hoi %p, je mag samen met %p %a0 slokken over jullie twee verdelen! Succes.",
      "Hey %p bind je schoenveters vast aan de spelers naast je.",
      "Hey %p, noem de kleur van je onderbroek. Voor iedere speler die dezelfde kleur onderbroek draagt mag je een slok uitdelen.",
      "Hii %p, wie vind jij de knapste speler aan tafel??? %a0 slokken voor jullie allebei ;)",
      "%p, jij beheert de komende drie nummers in de playlist. Veel plezier!",
      "%p, de komende twee keer dat jij moet drinken mag je een andere speler kiezen die het dubbele aantal met je mee drinkt. ",
      "Hii %p, drink %a0 slokken als je nog nooit The Lord of the Rings hebt gezien! Schande!",
      "Hii %p, deel %a0 slokken uit als je alle Harry Potter-films hebt gezien!",
      "Hey %p, wat is jouw grootste Guilty Pleasure???",
      "Hey %p, op wie was je als laatste verliefd?",
      "Hey %p, vertel ons eens: wanneer heb je voor het laatst gemasturbeerd? ",
      "Hey %p, wat is jouw meest gênante moment wat je op school hebt meegemaakt?",
      "Hey %p, waar heb je afgelopen week het hardst om gelachen?",
      "%p, ga een weddenschap met %p aan. Het onderwerp mag je zelf verzinnen, de inzet is een adtje.",
      "%p en %p zijn nu een koppel. Iedere keer als de een drinkt, drinkt de ander mee. ",
      "%p, roep heel hard 'Floor', de speler die als laatste de grond raakt krijgt %a0 slokken",
      "%p, doe je beste impressie van een naaktslak.",
      "%p, ga op handen en voeten een rondje om de tafel/door de kamer.",
      "%p, zing een zelfverzonnen serenade over de speler rechts van je.",
      "%p, doe nu je ogen dicht. De andere spelers veranderen iets aan de ruimte waar je nu bent. Spreek van tevoren af om hoeveel slokken je speelt. Raad je wat er veranderd is, dan mag je ze uitdelen, zo niet zijn ze voor jou.",
      "Hey %p, doe jouw beste impressie van een BN'er naar keuze.",
      "Hii %p, stuur een appje naar je ouders en vertel ze hoeveel je van ze houdt.",
      "Hii %p, jij mag niet meer praten tot een van de glazen aan tafel leeg is. Iedere keer dat je wel praat betekent dat %a0 slokken drinken.",
      "Hoi %p, ga alle andere spelers langs en kus ze. Voor iedere speler die je kust mag je twee slokken uitdelen. ",
      "Hoi %p, kies blind iemand uit je contactenlijst en stuur diegene een berichtje met je neus. Liever niet? %a0 slokken voor jou!",
      "Hoi %p, kies iemand uit je contacten en vraag of diegene vanavond nog mee komt spelen.",
      "Gefeliciteerd %p! Je hebt de PAPA-kaart gewonnen! Je mag vanaf nu op een door jouw gekozen moment een adtje aan iemand uitdelen. Veel plezier :)",
      "Hey %p jij mag vanaf de volgende ronde op een willekeurig moment je hand op tafel leggen. De andere spelers moeten zo snel mogelijk hun hand daarbovenop leggen. De laatste speler die zijn hand bovenop legt krijgt %a1 slokken!",
      "%p, begin met het neuriën van een liedje. De andere spelers moeten meeneurien zodra ze het herkennen. De laatste speler die neuriet of de spelers die het nummer niet herkennen drinken %a1 slokken. Kent meer dan de helft het niet, dan drink je ze zelf!",
      "%p en %p posten allebei een foto op hun insta-verhaal. De speler die na tien minuten de meeste weergaven heeft mag %a0 slokken uitdelen!",
      "%p en %p moeten beide een foto posten op instagram. De speler die na tien minuten de minste likes heeft krijgt een adtje!",
      "%p en %p! Let goed op! Leg zo snel mogelijk een voorwerp met de beginletter K op tafel, de speler die dit het snelste doet mag %a0 slokken uitdelen!",
      "Hii %p, tijd om te stijldansen met de speler rechts van je. De andere spelers bepalen of het goed genoeg is. Is het onvoldoende? Drink allebei %a0 slokken. Succes!",
      "Let op %p! Je krijgt 30 seconden om een voorwerp te vinden wat je de komende vijf minuten als hoofddeksel moet gebruiken. Lukt dit niet? %a0 slokken voor jou!",
      "%p, vertel een sterk verhaal (waargebeurd of verzonnen). De andere spelers mogen raden of het echt of verzonnen is. Iedereen die het fout heeft drinkt %a0 slokken",
      "%p, speel steen, papier, schaar met %p. De verliezer drinkt %a0 slokken en de winnaar mag er nog eens %a0 uitdelen aan de andere spelers!",
      "%p, maak een drankje klaar voor %p. Als 'ie lekker is mag je %a0 slokken uitdelen. Is 'ie niet lekker? %a0 slokken voor jou!",
      "Heyhoi %p, vertel je slechtste grap. Als er iemand lacht mag je %a0 slokken uitdelen, zo niet zijn ze voor jou.",
      "Heyhoi %p, doe een staredown met de speler tegenover je. De winnaar mag %a0 slokken uitdelen.",
      "Heyhoi %p, beschrijf je favoriete serie zonder de naam van de serie, acteurs of personages te noemen. Raden de andere spelers het goed? Dan mag je %a0 slokken uitdelen.",
      "%p, tijd voor een potje pispotten met %p. Winnaar ligt onder en mag %a0 slokken uitdelen.",
      "%p, doe een impressie van een van de spelers aan tafel. Raden de andere spelers wie je nadoet mag je %a0 slokken uitdelen, zo niet zijn ze van jou! ",
      "%p, beeld je favoriete film uit zonder te praten. Je krijgt 20 seconden. Wordt het geraden, mag je %a0 slokken uitdelen, zo niet zijn ze voor jou!",
      "Een vraag voor %p: wat is de tweede naam van %p? Heb je het goed, dan mag je %a0 slokken uitdelen!",
      "Een vraag voor %p: wat is de verjaardag van %p? Weet je het niet of heb je het fout? Schande! Drink %a0 slokken!",
      "Hoi %p, vertel ons eens: wat is het meest sexy aan jouw lichaam?",
      "Hey %p, wat is er nou het meest sexy aan %p?",
      "%p, app een (oud-)klasgenootje en vraag hem/haar uit op een date. Als hij/zij ja zegt moet iedereen adten. Liever niet appen/bellen? Je mag de opdracht afkopen voor %a1 slokken.",
      "%p, trek een kledingstuk uit! Liever niet? Drink %a1 slokken!",
      "%p, wissel van shirt met %p! Doen jullie dit niet? Allebei %a1 slokken!",
      "%p, wissel een kledingstuk met %p! Doen jullie dit niet? Allebei %a0 slokken!",
      "Wassup %p? Maak een selfie en post 'm direct op insta (en laat hem minimaal een halfuur online staan). Doe je dit? Dan mag je %a1 slokken uitdelen! Doe je het niet? Dan zijn ze allemaal voor jou!",
      "Hey %p, bel of app een ex en zeg dat je nog een t-shirt van hem/haar krijgt! Doe je dit niet? %a1 slokken voor jou!",
      "Hii %p, lees je laatste insta-dm voor! Doe je dit niet? %a0 slokken voor jou!",
      "Hii %p, kies een speler uit om sokken mee te wisselen. Doen jullie dit niet? Beide %a1 slokken!",
      "Hey %p, verklaar de iemand in de ruimte de liefde in het Frans. Als je dit niet doet krijg je %a0 slokken!",
      "%p, haal voor iedereen die een nieuw drankje. Geen zin? Neem dan een adtje en haal alleen voor jezelf.",
      "%p, de andere spelers mogen een filmpersonage voor jou uitkiezen. De komende vijf minuten speel jij die rol. . Geen zin? Dan krijg je %a0 slokken!",
      "Hey %p, de komende drie minuten moet je constant als Yoda praten. Als je dit niet doet krijg je %a1 slokken! Jou veel succes ik wens!",
      "%p, neem nu een foto en stuur die naar je derde insta-DM in je lijst. Geen zin? Adtje!",
      "%p, neem nu een selfie en stel die in als je WhatsApp-profiel foto. Liever niet? %a0 slokken voor jou!",
      "%p, laat je beste dansmove zien aan de andere spelers! Doe je het niet of niet goed genoeg? %a0 slokken drinken!",
      "Hii %p, de komende vijf minuten moet je verplicht met een Russisch accent praten. Iedere keer dat je dit niet doet krijg je %a0 slokken!",
      "Hii %p, de komende vijf minuten moet je verplicht met een Frans accent praten. Iedere keer dat je dit niet doet krijg je %a0 slokken!",
      "Hoi %p, de komende vijf minuten moet je verplicht met een Italiaans accent praten. Iedere keer dat je dit niet doet krijg je %a0 slokken!",
      "Hii %p, de komende vijf minuten moet je verplicht met een Duits accent praten. Iedere keer dat je dit niet doet krijg je %a0 slokken!",
      "Hey %p, doe een handstand! De andere spelers bepalen of het goed genoeg is. Onvoldoende? %a0 slokken voor jou!",
      "%p, je moet armpje drukken tegen %p. De verliezer moet %a0 slokken drinken!",
      "%p, houd een duimworstel-wedstrijd met %p. De verliezer moet %a0 slokken drinken!",
      "%p, de andere spelers mogen bepalen aan wie van jouw volgers jij een (spicy) insta-Dm mag sturen... Durf je niet? %a1 slokken voor jou!",
      "%p, het is tijd voor een prankcall naar iemand naar eigen keuze. De andere spelers mogen het onderwerp van het gesprek bepalen.  Durf je niet? Dan betekent dit een adtje voor jou!",
      "Hii %p, stuur een videoboodschap naar je beste vriend uit groep vijf van de basisschool.  Als je dit niet doet krijg je %a0 slokken!",
      "Hii %p, de speler rechts van jou mag je een voorwerp toefluisteren dat jij moet beschrijven zonder het woord zelf te zeggen. Wordt het binnen 30 seconden geraden mag je %a0 uitdelen, zo niet zijn ze voor jou. Als je het woord wel hardop zegt ben je een valsspeler en krijg je een adtje.",
      "Iedereen kleiner dan %p drinkt %a0 slokken!",
      "Iedereen langer dan %p drinkt %a0 slokken!",
      "Iedereen meer sekspartners dan %p drinkt %a0 slokken!",
      "Iedereen met een rood kledingstuk drinkt %a0 slokken!",
      "Iedereen met een wit kledingstuk drinkt %a0 slokken!",
      "Iedereen met een zwart kledingstuk drinkt %a0 slokken!",
      "Iedereen met blond haar drinkt %a0 slokken!",
      "Iedereen met een zusje drinkt %a0 slokken!",
      "Iedereen met gescheiden ouders %a0 slokken!",
      "Iedereen met een broertje %a0 slokken!",
      "Iedereen die in de afgelopen twee maanden in het buitenland is geweest drinkt nu %a0 slokken!",
      "Iedereen die op dit moment Adidas draagt drinkt %a0 slokken!",
      "Iedereen die de afgelopen maand heeft gehuild krijgt %a0 slokken!",
      "Iedereen die ooit gehuild heeft om een film drinkt %a0 slokken!",
      "Iedereen wiens leeftijd een even getal is mag %a0 slokken uitdelen!",
      "Iedereen wiens leeftijd een oneven getal is mag %a1 slokken uitdelen!",
      "Iedereen die ingeschreven staat bij een sportvereniging of -school mag %a0 slokken uitdelen! Lekker bezig, pik!",
      "Iedereen op dit moment geen ondergoed draagt mag twee keer %a1 slokken uitdelen!",
      "Iedereen met ondergoed aan drinkt %a0 slokken!",
      "Iedereen die vandaag of gisteren een salade heeft gegeten mag %a0 slokken uitdelen!",
      "Iedereen die ooit in Biggekerke is geweest mag %a1 drinken! Proost!",
      "Iedereen die afgelopen maand een date heeft gehad drinkt %a0 slokken!",
      "Alle jongens drinken %a0 slokken!",
      "Alle meisjes drinken %a0 slokken!",
      "Alle maagden drinken %a0 slokken!",
      "Alle zittenblijvers drinken %a0 slokken!",
      "Alle spelers met een A in hun naam drinken %a0 slokken!",
      "Alle spelers met een L in hun naam  drinken %a0 slokken!",
      "Alle spelers met een achternaam van meer dan zes letters drinken het aantal slokken dat ze meer hebben.",
      "Alle gingers drinken %a0 slokken!",
      "Alle brunettes delen %a0 slokken uit!",
      "Drink allemaal evenveel slokken als het aantal keren dat je praktijkexamen voor je rijbewijs hebt gedaan!",
      "%p, drink evenveel slokken als het aantal exen dat je hebt gehad!",
      "%p drinkt evenveel slokken als het aantal sekspartners dat hij/zij heeft gehad!",
      "%p, deel evenveel slokken uit als het aantal voornamen dat je hebt!",
      "%p, neem evenveel slokken als het aantal tieten in de kamer!",
      "De speler met de hoogste studieschuld drinkt %a0 slokken!",
      "De host van vanavond drinkt %a0 slokken!",
      "De eerstvolgende die naar de wc gaat krijgt %a0 slokken!",
      "De speler die het langst geen feestje heeft gegeven drinkt %a1 slokken!",
      "De speler met de meest SEXY moeder mag %a1 slokken uitdelen!",
      "Handen omhoog! De speler die het laatst zijn handen in de lucht heeft, krijgt %a0 slokken!",
      "Opstaan! De speler die het laatst opgestaan is, krijgt %a0 slokken!",
      "De speler die de vorige keer host is geweest mag %a0 slokken uitdelen! Goed gedaan!",
      "De speler met het langste haar drinkt %a0 slokken!",
      "De speler met het kortste haar mag %a0 slokken uitdelen!",
      "Dames! (en heren…), als je vanavond een string draagt, drink %a0 slokken!",
      "Leg allemaal je telefoon op tafel, de speler die als eerste een notificatie krijgt neemt %a0 slokken!",
      "De grootste nerd van de groep krijgt %a0 slokken!",
      "De speler met de meeste paar schoenen neemt nu %a0 slokken!",
    ],
    // Stemrecht
    [
      "Je kunt je dromen opnemen OF Je hebt altijd een magisch gevulde koelkast. De verliezer drinkt %a0 slokken",
      "Je partner wordt porno-acteur OF Je partner voelt altijd koud aan. De verliezer drinkt %a0 slokken",
      "Je draagt elke dag een ongewoon hoofddeksel OF je moet elke week de ridderzaal schoonmaken. De verliezer drinkt %a0 slokken",
      "Je moet elk half jaar verhuizen OF Je moet altijd achteruit lopen. De verliezer drinkt %a0 slokken",
      "één jaar geen mondverzorging OF één jaar dezelfde onderbroek aan. De verliezer drinkt %a0 slokken",
      "Je bent analfabeet OF Je hebt schubben over je hele lijf. De verliezer drinkt %a0 slokken",
      "Altijd een clown naast je bed OF Je neus groeit als je liegt. De verliezer drinkt %a0 slokken",
      "Je zweet olijfolie OF Al je eten is te pittig. De verliezer drinkt %a0 slokken",
      "Altijd een papegaai op je schouder OF Je enige vervoersmiddel is een paard. De verliezer drinkt %a0 slokken",
      "Je hebt een rattenstaart OF Je moet altijd buiten poepen en plassen. De verliezer drinkt %a0 slokken",
      "Iedereen hoort wat je denkt OF Jij hoort wat iedereen denkt. De verliezer drinkt %a0 slokken",
      "Je plast 3x per week in bed OF Je moet elke avond om 23:00 naar bed. De verliezer drinkt %a0 slokken",
      "Je kunt de lokale weersomstandigheden bepalen OF Je kunt op elk moment onzichtbaar worden. De verliezer drinkt %a0 slokken",
      "Je moet eenmalig je nagels eruit laten trekken OF Je moet elke ochtend naakt in de brandnetels rollen. De verliezer drinkt %a0 slokken",
      "Alle dieren voelen zich seksueel tot je aangetrokken OF Je gebruikt schuurpapier als WC-papier. De verliezer drinkt %a0 slokken",
      "Al je kleren zijn 3 maten te klein OF Je zegt alles 2 keer. De verliezer drinkt %a0 slokken",
      "Al je uitgaven in muntjes van 5 cent OF Je hebt altijd windkracht 7 tegen. De verliezer drinkt %a0 slokken",
      "Je kan alle muziekinstrumenten bespelen OF Je kan alle talen spreken. De verliezer drinkt %a0 slokken",
      "Je bent doodsbang voor prullenbakken OF Je sokken zijn altijd nat. De verliezer drinkt %a0 slokken",
      "Je moet altijd ovenwanten aan OF Je mag max. 100 woorden per dag zeggen. De verliezer drinkt %a0 slokken",
      "Geen warm water in huis OF Alleen maar TL-verlichting. De verliezer drinkt %a0 slokken",
      "Je hebt een blok aan je been OF Je valt altijd met de deur in huis. De verliezer drinkt %a0 slokken",
      "Alles wat je zegt moet rijmen OF Je spendeert de rest van je leven in Vlijmen. De verliezer drinkt %a0 slokken",
      "Je loopt op handen en voeten OF Je ogen zitten aan de zijkant van je hoofd. De verliezer drinkt %a0 slokken",
      "Je hoort altijd het geluid van een stofzuiger in je hoofd OF Je moet 1 keer per week buiten slapen. De verliezer drinkt %a0 slokken",
      "Je hebt een kalkoenlel OF Je mag jezelf alleen wassen met knakworstensap. De verliezer drinkt %a0 slokken",
      "Iedere dag de buren op visite voor een kopje koffie OF Altijd als je danst, dans je de macarena. De verliezer drinkt %a0 slokken",
      "Je huis is altijd extreem versierd met kerstdecoratie OF Je verblijft vanaf nu twee weken in een levende kerststal. De verliezer drinkt %a0 slokken",
      "Nooit meer warm eten OF Alles wat je leest, lees je hardop. De verliezer drinkt %a0 slokken",
      "Een keer per maand verdwijnt onverwacht je kleding OF Je hebt altijd de hik als je wakker bent. De verliezer drinkt %a0 slokken",
      "Je moet aan elk kind vertellen dat Sinterklaas niet bestaat OF Je hebt altijd in elke schoen 1 pepernoot. De verliezer drinkt %a0 slokken",
      "Alles wat je zegt wordt ook in het Duits nagesynchroniseerd OF Je wordt op straat altijd achtervolgd door een draaiorgel. De verliezer drinkt %a0 slokken",
      "Niemand lacht ooit om wat je zegt OF Je moet lachen als iemand anders huilt. De verliezer drinkt %a0 slokken",
      "Je bilnaad loop door tot je nek OF Je poetst je tanden elke dag met filet americain. De verliezer drinkt %a0 slokken",
      "Je hebt 100 bijna identieke sleutels aan je sleutelbos OF Je geeft bij 3 zoenen altijd de derde op de mond. De verliezer drinkt %a0 slokken",
      "Je lichaamshuid is van krokettenkorst OF Er loopt altijd een dwerg naast je die zegt dat je liegt. De verliezer drinkt %a0 slokken",
      "Er worden iedere nacht 5 muggen losgelaten in je slaapkamer OF Je kruipt altijd voor in de rij. De verliezer drinkt %a0 slokken",
      "Er staat een paard in de gang OF Je bent een bloemetjesgordijn. De verliezer drinkt %a0 slokken",
      "Je woont op de 94ste verdieping van een flat zonder lift OF Al je digitale communicatie moet vanaf vandaag via handgeschreven brief. De verliezer drinkt %a0 slokken",
      "Je draagt alleen maar kleding met een tijgerprint OF Iedere zaterdagavond speel je bingo in een bejaardentehuis. De verliezer drinkt %a0 slokken",
      "Je gaat hard knorren als je geil bent OF Je wordt elke dag in een vrachtwagen vol varkens vervoerd naar je werk. De verliezer drinkt %a0 slokken",
      "Overal waar je binnenkomt moet je een schwalbe maken OF Alles wat je doet wordt becommentarieerd door Jack van Gelder. De verliezer drinkt %a0 slokken",
      "Je moet elke week één bouquet roman lezen OF Al je gebruiksnamen en emailadressen beginnen voor de rest van je leven met piemelboy69. De verliezer drinkt %a0 slokken",
      "Je moet de basisschool overdoen OF Je praat tegen iedereen zoals je tegen baby’s praat. De verliezer drinkt %a0 slokken",
      "Je glowt in the dark OF Als je muziek opzet komt de band automatisch live in je woonkamer optreden. De verliezer drinkt %a0 slokken",
      "Wanneer je loopt draag je een dienblad OF Je moet op al je eten sabbelen. De verliezer drinkt %a0 slokken",
      "Je hebt verspreid over de dag 10 minuten om te eten OF Je moet elke dag een uur met aandacht naar TEL-SELL reclames kijken. De verliezer drinkt %a0 slokken",
      "Je hebt een robot-butler OF Je onthoudt alles wat je leest. De verliezer drinkt %a0 slokken",
      "Er ontstaat een elektrische schok als je iemand kust OF Je slaapt altijd op een vochtig matras. De verliezer drinkt %a0 slokken",
      "Je moet ieder weekend met een plakje brie onder je tong slapen OF Je bent ziek op alle nationale feestdagen. De verliezer drinkt %a0 slokken",
      "Je wordt elke dag wakker met “Wake me up before you go-go” van Wham OF Je spuit elke dag een bus haarspray in je haar. De verliezer drinkt %a0 slokken",
      "Je hebt altijd het gevoel dat je moet niezen (maar het lukt niet) OF De onderkant van je schoenen is spekglad. De verliezer drinkt %a0 slokken",
      "Je snijtanden worden drie keer zo groot OF Je drinkt dagelijks een glas dierlijk bloed. De verliezer drinkt %a0 slokken",
      "Je moet altijd een spoor van broodkruimels achterlaten OF Er wonen zeven dwergen in je huis. De verliezer drinkt %a0 slokken",
      "Je maakt elk uur het geluid van een koekoeksklok OF Je kunt geen klok meer lezen. De verliezer drinkt %a0 slokken",
      "Al je spullen zitten in kannen en kruiken OF Je loopt altijd tegen de lamp. De verliezer drinkt %a0 slokken",
      "Als je scheldt of vloekt moet je je mond spoelen met zeep OF Je mag pas praten als je van iemand de beurt hebt gekregen. De verliezer drinkt %a0 slokken",
      "Je moet één zintuig afstaan OF J kunt d lttr “ ” nit mr uitsprkn of schrijvn. De verliezer drinkt %a0 slokken",
      "Elke partner die je ooit hebt, speelt – zeer fanatiek – blokfluit OF Je moet in het openbaar vervoer altijd bij een vreemde op schoot zitten. De verliezer drinkt %a0 slokken",
      "Je eet alleen nog maar vliegtuigeten OF Alle muziek klinkt als een polyfone ringtone. De verliezer drinkt %a0 slokken",
    ],
    // Never Have I Ever
    [
      "Never have I ever seks gehad op de eerste date. Zo ja, neem %a0 slokken",
      "Never have I ever in de douche geplast. Zo ja, neem %a0 slokken",
      "Never have I ever een verkeersboete gehad. Zo ja, neem %a0 slokken",
      "Never have I ever schade aan andermans auto gereden. Zo ja, neem %a0 slokken",
      "Never have I ever iemand gedumpt over WhatsApp. Zo ja, neem %a0 slokken",
      "Never have I ever nudes verstuurd. Zo ja, neem %a0 slokken",
      "Never have I ever een vakantieliefde gehad. Zo ja, neem %a0 slokken",
      "Never have I ever de nieuwe partner van een ex gestalked op social media. Zo ja, neem %a0 slokken",
      "Never have I ever uit de club/kroeg gezet. Zo ja, neem %a0 slokken",
      "Never have I ever met de ex van een vriend uit geweest. Zo ja, neem %a0 slokken",
      "Never have I ever andermans tandenborstel gebruikt. Zo ja, neem %a0 slokken",
      "Never have I ever gekotst door te veel alcohol. Zo ja, neem %a0 slokken",
      "Never have I ever naar een naaktstrand geweest. Zo ja, neem %a0 slokken",
      "Never have I ever mijn ouders betrapt. Zo ja, neem %a0 slokken",
      "Never have I ever betrapt geweest. Zo ja, neem %a0 slokken",
      "Never have I ever gelogen tijdens dit spelletje. Zo ja, neem %a0 slokken",
      "Never have I ever drugs gedaan. Zo ja, neem %a0 slokken",
      "Never have I ever met iemand naar bed gegaan waarvan ik de naam niet meer weet. Zo ja, neem %a0 slokken",
      "Never have I ever seks in het openbaar gehad. Zo ja, neem %a0 slokken",
      "Never have I ever iets gestolen uit een winkel. Zo ja, neem %a0 slokken",
      "Never have I ever iets geleend en nooit meer teruggegeven. Zo ja, neem %a0 slokken",
      "Never have I ever iemand in het ziekenhuis doen belanden. Zo ja, neem %a0 slokken",
      "Never have I ever stiekem door iemands telefoon gegaan. Zo ja, neem %a0 slokken",
      "Never have I ever iemand van hetzelfde geslacht gekust. Zo ja, neem %a0 slokken",
      "Never have I ever dronken naar de speeltuin gegaan. Zo ja, neem %a0 slokken",
      "Never have I ever geslijmd bij de docent voor een beter cijfer. Zo ja, neem %a0 slokken",
      "Never have I ever een gênante video op YouTube gezet. Zo ja, neem %a0 slokken",
      "Never have I ever geld gestolen van mijn ouders. Zo ja, neem %a0 slokken",
      "Never have I ever een Tinder-date gehad. Zo ja, neem %a0 slokken",
      "Never have I ever vreemdgegaan. Zo ja, neem %a0 slokken",
      "Never have I ever mijn geslachtdeel opgemeten. Zo ja, neem %a0 slokken",
      "Never have I ever iemand geslagen zonder reden. Zo ja, neem %a0 slokken",
      "Never have I ever aangevallen door iemands huisdier. Zo ja, neem %a0 slokken",
      "Never have I ever bodyshots gedaan. Zo ja, neem %a0 slokken",
      "Never have I ever handboeien omgehad. Zo ja, neem %a0 slokken",
      "Never have I ever in m'n broek geplast van het lachen. Zo ja, neem %a0 slokken",
      "Never have I ever een prankcall gedaan. Zo ja, neem %a0 slokken",
      "Never have I ever gezegd dat ik nóóít meer zou drinken. Zo ja, neem %a0 slokken",
      "Never have I ever op de bar gedanst. Zo ja, neem %a0 slokken",
      "Never have I ever ge-skinny-dipped. Zo ja, neem %a0 slokken",
      "Never have I ever dickpicks verstuurd. Zo ja, neem %a0 slokken",
      "Never have I ever door rood gereden. Zo ja, neem %a0 slokken",
      "Never have I ever tegen een glazen deur gelopen. Zo ja, neem %a0 slokken",
      "Never have I ever iets afgezegd wegens een kater. Zo ja, neem %a0 slokken",
      "Never have I ever gefouilleerd door de douane op de luchthaven. Zo ja, neem %a0 slokken",
      "Never have I ever in slaap gevallen tijdens de seks. Zo ja, neem %a0 slokken",
      "Never have I ever gelogen over mijn leeftijd. Zo ja, neem %a0 slokken",
      "Never have I ever naar een stripclub geweest. Zo ja, neem %a0 slokken",
      "Never have I ever een nachtje doorgehaald voor studie. Zo ja, neem %a0 slokken",
    ],
    // Most Likely To
    [
      "Wie van jullie zou als eerste kannibalisme proberen?",
      "Wie van jullie zou als eerste een kind krijgen?",
      "Wie van jullie zou als eerste in een bargevecht terechtkomen?",
      "Wie van jullie zou als eerste overvallen worden?",
      "Wie van jullie zou als eerste trouwen?",
      "Wie van jullie zou als eerste aangevallen worden door een ex?",
      "Wie van jullie zou als eerste de hele groep in de problemen brengen?",
      "Wie van jullie zou als eerste zwanger raken uit een one-night-stand?",
      "Wie van jullie zou als eerste vast komen te zitten in een speeltoestel?",
      "Wie van jullie zou als eerste een meisje in de kroeg regelen?",
      "Wie van jullie zou als eerste stoppen met zijn/haar studie?",
      "Wie van jullie zou als eerste dakloos worden?",
      "Wie van jullie zou als eerste een hele week niet douchen?",
      "Wie van jullie zou als eerste een nachtje doorhalen om te studeren?",
      "Wie van jullie zou als eerste kotsen door teveel alcohol?",
      "Wie van jullie zou als eerste op vakantie gaan naar Mars?",
      "Wie van jullie zou als eerste op een blind date gaan?",
      "Wie van jullie zou als eerste in de gevangenis belanden?",
      "Wie van jullie zou als eerste minister-president worden?",
      "Wie van jullie zou als eerste emigreren?",
      "Wie van jullie zou als eerste in een 'Prins-uit-Senegal-spammail' trappen?",
      "Wie van jullie zou als eerste terug gaan naar de middelbare school als docent?",
      "Wie van jullie zou als eerste failliet gaan?",
      "Wie van jullie zou als eerste BDSM-meester(es) worden?",
      "Wie van jullie zou als eerste kroeghouder worden?",
      "Wie van jullie zou als eerste in de drugshandel eindigen?",
      "Wie van jullie zou als eerste een vuurwapen in bezit hebben?",
      "Wie van jullie zou als eerste in slaap te vallen tijdens de seks?",
      "Wie van jullie zou als eerste verliefd te worden op het broertje/zusje van zijn/haar beste vriend?",
      "Wie van jullie zou als eerste uit een boom te vallen?",
      "Wie van jullie zou als eerste zijn/haar benen te breken?",
      "Wie van jullie zou als eerste verliefd te worden op een stripper?",
      "Wie van jullie zou als eerste als sekswerker eindigen?",
      "Wie van jullie zou als eerste naar de hoeren gaan?",
      "Wie van jullie zou als eerste van de trap vallen?",
      "Wie van jullie zou als eerste in slaap vallen in de trein en je station missen?",
      "Wie van jullie zou als eerste meedoen aan een talentenjacht op tv?",
      "Wie van jullie zou als eerste eindigen als porno-acteur/-actrice?",
      "Wie van jullie zou als eerste zijn/haar baas uitschelden en ontslag nemen?",
      "Wie van jullie zou als eerste een vreselijke pestkop zijn?",
      "Wie van jullie zou als eerste aangevallen worden door een huisdier?",
      "Wie van jullie zou als eerste in het geheim een alien zijn?",
      "Wie van jullie zou als eerste in zijn/haar neus peuteren en het opeten?",
      "Wie van jullie zou als eerste alles op het spel te zetten voor een weddenschap?",
      "Wie van jullie zou als eerste honden- of kattenvoer eten?",
      "Wie van jullie zou als eerste nooit een broek aanhebben tijdens videomeetings?",
      "Wie van jullie zou als eerste in zijn eentje zijn eigen verjaardagstaart op te eten?",
      "Wie van jullie zou als eerste vaste klant worden van de plaatselijke snackbar?",
      "Wie van jullie zou als eerste zwaarder dan 150kg wegen?",
      "Wie van jullie zou als eerste een lievelingetje van de docent zijn?",
      "Wie van jullie zou als eerste stiekem gesprekken afluiisteren?",
      "Wie van jullie zou als eerste de wereld te vernietigen?",
      "Wie van jullie zou als eerste voorzitter zijn van de Phineas and Ferb-fanclub?",
      "Wie van jullie zou als eerste voorzitter zijn van de Frans Bauer-fanclub?",
      "Wie van jullie zou als eerste naar een Yes-R concert gaan?",
      "Wie van jullie zou als eerste naar een concert van Stef Ekkel gaan?",
      "Wie van jullie zou als eerste naar Thunderdome gaan?",
      "Wie van jullie zou als eerste naar de huishoudbeurs gaan?",
      "Wie van jullie zou als eerste een Neo-Nazi worden?",
      "Wie van jullie zou als eerste ruzie krijgen met de BOA's?",
      "Wie van jullie zou als eerste een baan krijgen als BOA?",
      "Wie van jullie zou als eerste de partner van Mark Rutte worden?",
      "Wie van jullie zou als eerste aanhanger van communisme worden?",
      "Wie van jullie zou als eerste naar bed gaan met Thierry Baudet?",
      "Wie van jullie zou als eerste flauwvallen als ze een celebrity ontmoeten?",
      "Wie van jullie zou als eerste acht keer falen voor het rij-examen?",
      "Wie van jullie zou als eerste een 510-score halen op de CiTo-Toets?",
      "Wie van jullie zou als eerste verliefd worden op zijn/haar docent?",
      "Wie van jullie zou als eerste seks hebben voor een voldoende?",
      "Wie van jullie zou als eerste seks hebben voor promotie?",
      "Wie van jullie zou als eerste zijn/haar dood te faken?",
      "Wie van jullie zou als eerste shopliften?",
      "Wie van jullie zou als eerste een overval te plegen?",
      "Wie van jullie zou als eerste tegen zichzelf praten?",
      "Wie van jullie zou als eerste zichzelf ziekmelding op werk om iets leuks te gaan doen?",
      "Wie van jullie zou als eerste op vakantie gaan naar Tadzikistan?",
      "Wie van jullie zou als eerste millionair worden?",
      "Wie van jullie zou als eerste dokter worden?",
      "Wie van jullie zou als eerste een kinderprogramma op tv maken?",
      "Wie van jullie zou als eerste een gokker worden?",
      "Wie van jullie zou als eerste beroemd worden?",
      "Wie van jullie zou als eerste kunstenaar worden?",
      "Wie van jullie zou als eerste gigolo worden?",
      "Wie van jullie zou als eerste gold digger worden?",
      "Wie van jullie zou als eerste monnik of non worden?",
      "Wie van jullie zou als eerste comedian worden?",
      "Wie van jullie zou als eerste stripper worden?",
      "Wie van jullie zou als eerste verslaafd raken aan drugs?",
      "Wie van jullie zou als eerste verslaafd raken aan fast food?",
      "Wie van jullie zou als eerste verslaafd raken aan koffie?",
      "Wie van jullie zou als eerste een hele dag in pyjama blijven lopen?",
      "Wie van jullie zou als eerste fanatiek vierdaagse-loper worden?",
      "Wie van jullie zou als eerste een nacht door te halen om te gamen?",
      "Wie van jullie zou als eerste workaholic te worden?",
      "Wie van jullie zou als eerste trouwen om het geld?",
      "Wie van jullie zou als eerste trouwen met iemand die gehaat wordt door al zijn/haar vrienden en familieleden?",
      "Wie van jullie zou als eerste in een dronken bui met een vreemde trouwen?",
      "Wie van jullie zou als eerste 1.000.000 volgers op TikTok hebben?",
      "Wie van jullie zou als eerste een genante tattoo laten zetten?",
      "Wie van jullie zou als eerste kippenboer worden?",
      "Wie van jullie zou als eerste in Masterchef te zien zijn?",
      "Wie van jullie zou als eerste te zien zijn in 'Help! Mijn Man is Klusser!'?",
      "Wie van jullie zou als eerste volledig bedekt zijn met tattoeages?",
      "Wie van jullie zou als eerste zijn/haar huis in de fik zetten tijdens het koken?",
      "Wie van jullie zou als eerste meer dan vijf kinderen te krijgen?",
      "Wie van jullie zou als eerste 100 jaar oud worden?",
      "Wie van jullie zou als eerste verhuizen naar Antarctica?",
      "Wie van jullie zou als eerste verhuizen naar het platteland?",
      "Wie van jullie zou als eerste alleen een horrorfilm kijken?",
      "Wie van jullie zou als eerste alleen nog maar romcoms kijken?",
      "Wie van jullie zou als eerste alleen sterven?",
      "Wie van jullie zou als eerste verliefd worden op een twintig jaar ouder persoon?",
      "Wie van jullie zou als eerste nooit zijn goede voornemens behalen?",
      "Wie van jullie zou als eerste vreemdgaan?",
      "Wie van jullie zou als eerste een dief helpen ontsnappen?",
      "Wie van jullie zou als eerste seks op het strand te hebben?",
      "Wie van jullie zou als eerste een hele strenge ouder zijn?",
      "Wie van jullie zou als eerste alleen nog maar bier en pizza te eten/drinken?",
      "Wie van jullie zou als eerste gillen om een spin?",
      "Wie van jullie zou als eerste een knorrige oude man te worden?",
      "Wie van jullie zou als eerste naar Hogwarts gaan?",
      "Wie van jullie zou als eerste stiekem wat bijverdienen als escort?",
    ],
    // Medusa
    [
      "Yess, op naar een rondje Medusa! Kijk allemaal naar de vloer, %p roept op een willekeurig moment GO! Op dat moment kijkt iedereen van de grond op en kijkt in de richting van een andere speler. Kijken jullie elkaar in de ogen aan? Dan drinken jullie allebei %a0 slokken!",
    ],
    // Lepeltje Lepeltje
    [
      "En nu door naar een rondje Lepeltje Lepeltje! %p, pak je drankje erbij en neem gelijk een extra lege beker en een theelepeltje mee. (Tip: een theedoek is misschien ook handig). Je krijgt een minuut de tijd om zoveel mogelijk van jouw mixdrankje in de andere beker te lepelen. De bekers moeten op tafel blijven staan. Alles wat er in jouw beker overblijft moet je daarna adten. Alles in de andere beker mag je aan een vriend doneren. Succes!",
    ],
    // Vingeren
    [
      "Zet allereerst een drankje in het midden van de tafel, zo dat iedereen erbij kan. Het spel kan beginnen als iedereen met één vinger het glas aanraakt. Er wordt nu afgeteld en je kunt kiezen of je je vinger op het glas houdt. Telkens moet één persoon raden hoeveel vingers er nog op het drankje blijven liggen. De speler die het aantal vingers moet raden, telt af en op één noemt hij het aantal vingers dat hij denkt dat er aan het glas blijven zitten. Is het goed geraden? Dan mag je uit het spel. Zo niet, blijf je meespelen. De beurt gaat dan naar de volgende speler, etc. De speler die als laatste overblijft (en dus het slechtst heeft geraden), moet het glas adten.",
    ],
    // Big
    ["Helaas! %p, jij bent De Big. Drink in een keer je glas leeg. Proost!"],
    // Baas
    [
      "Gefeliciteerd! %p, jij bent vanavond De Baas. Kies een speler uit die zijn glas in een keer leeg moet drinken!",
    ],
  ],
};

const beerput = {
  meta: {
    types: Array(11).fill("beerput"),
    probabilities: [4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 0],
  },
  cards: [
    ["Neem %a0 slokken uit de beerput!"],
    ["Doneer %a0 slokken aan de beerput!"],
    ["Neem %a0 slokken uit je eigen glas!"],
    ["Deel %a0 slokken uit de beerput uit!"],
    [
      "Deel %a0 slokken uit aan een andere speler! Deze mag ze uit zijn éígen glas drinken.",
    ],
    [
      "Vul de beerput aan met drank (met of zonder alcohol) uit de voorraadkast!",
    ],
    ["Ff rust, deze ronde gebeurt er niets."],
    [
      "De spelrichting draait om! Speel zelf nog eens en geef de beurt daarna door in tegengestelde richting.",
    ],
    ["FLOOOOOOOOOOOOOOOOORRRRRRR!!!!!!!!"],
    [
      "Je mag een wedstrijdje duimworstelen met de speler tegenover je. De winnaar mag %a0 slokken aan de beerput schenken.",
    ],
    [
      "Allereerst een aantal voorbereidingen: ga met alle spelers aan een tafel zitten en zorg dat iedereen een mixdrankje bij zich heeft (geen bier dus!). Zorg daarnaast voor een extra glas (de beerput), vul die tot de helft met een mixdrankje en zet die in het midden van de tafel. Het doel van het spel is om zo snel mogelijk je eigen glas leeg te krijgen. Dit kan door te drinken en door het vullen van het centrale glas. Als het centrale glas leeg is mag de speler die hem leeg heeft gedronken hem weer tot halverwege vullen. De rest van het spel legt zichzelf uit. %p  mag van start!",
    ],
  ],
};
